# Vectorization basics

In [15]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [16]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorised version : "+ str(1000*(toc-tic)) + "ms") 
print(c)


Vectorised version : 2.9571056365966797ms
249862.43088321204


In [17]:
c=0
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc = time.time()

print("For-loop version : "+ str(1000*(toc-tic)) + "ms")   
print(c)

For-loop version : 452.7866840362549ms
249862.4308832133


# Script for python broadcasting

In [38]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [39]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [40]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


# Python Vectors

In [2]:
import numpy as np

a = np.random.randn(5)
print(a)

[-0.21650813  1.47597657 -0.32387152  0.23619447  0.47010271]


In [3]:
print(np.shape(a))

(5,)


In [4]:
print(a.T)

[-0.21650813  1.47597657 -0.32387152  0.23619447  0.47010271]


In [5]:
print(np.dot(a,a.T))

2.607059747359658


In [6]:
a = np.random.randn(5,1)
print(a)
print(a.shape)

[[ 1.79323084]
 [ 1.54892801]
 [-0.26695086]
 [-1.4434309 ]
 [-1.94733471]]
(5, 1)


In [7]:
print(a.T)

[[ 1.79323084  1.54892801 -0.26695086 -1.4434309  -1.94733471]]


In [8]:
print(np.dot(a,a.T))

[[ 3.21567685  2.77758547 -0.47870452 -2.58840481 -3.49202066]
 [ 2.77758547  2.39917797 -0.41348767 -2.23577054 -3.01628127]
 [-0.47870452 -0.41348767  0.07126276  0.38532512  0.51984268]
 [-2.58840481 -2.23577054  0.38532512  2.08349276  2.81084309]
 [-3.49202066 -3.01628127  0.51984268  2.81084309  3.79211248]]


In [9]:
assert(a.shape == (5,1))

In [10]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[ 0.312973    3.27387244  1.51961154]
 [ 0.50268085  1.21003456 -1.42205723]
 [-0.36616081  0.11258139  0.18746957]]


# Check

In [22]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)

In [23]:
print(A)
print(B)
print(B.shape)

[[-0.2373337   2.35592699 -1.99025945]
 [ 0.28147592 -1.36264587 -0.24988378]
 [ 1.32555065 -1.59981474 -0.69270674]
 [ 1.05633626 -0.18934999  0.62584135]]
[[ 0.12833384]
 [-1.33105372]
 [-0.96697083]
 [ 1.49282762]]
(4, 1)
